version: '3.3'
services:

  node-manager:
    container_name: node-manager
    hostname: node-manager
    image: 192.168.100.242:5012/orspo/rigel/service/node-runner:1.0.5_1.3.0
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${NODE_MANAGER_PORT}
      - CONFIG=/config/config.json
      - FMT_LEVEL=info,actix_web=error
      - GST_PLUGIN_PATH=/opt/node_manager/plugins
    volumes:
      - ./node-manager/config:/config
      - ./node-manager/plugins:/opt/node_manager/plugins
      - ./node-manager/runtime:/opt/node_manager/runtime
      - /archive:/opt/node_manager/runtime/archive
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: 192.168.100.242:5012/orspo/rigel/service/rabbitmq:rabbitmq-3.11.0-management
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  postgres:
    container_name: postgres
    hostname: postgres
    image: 192.168.100.242:5012/orspo/rigel/service/postgres-images:postgres-16
    user: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - 5432:5432
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  api-gateway-tls:
    container_name: api-gateway-tls
    hostname: api-gateway-tls
    image: 192.168.100.242:5012/orspo/rigel/service/api-gateway:1.1.9
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${API_GATEWAY_TLS_PORT}
      - PROXYLIST=config/proxylist.yml
      - FMT_LEVEL=info,tower_http=warn
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - TLS_CERT=cert/cert.pem
      - TLS_KEY=cert/key.pem
      - AUTH_RSA_PUBLIC_FILE=cert/pubkey.pem
      - DROP_CONNECTION_WHEN_TOKEN_EXPIRES=no
    ports:
      - 8179:8179
    volumes:
      - ./api-gateway/tls-cert:/cert
      - ./api-gateway/config:/config
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    image: 192.168.100.242:5012/orspo/rigel/service/api-gateway:1.1.9
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${API_GATEWAY_PORT}
      - PROXYLIST=config/proxylist.yml
      - FMT_LEVEL=info,tower_http=warn
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
    ports:
      - 8189:8189
    volumes:
      - ./api-gateway/tls-cert:/cert
      - ./api-gateway/config:/config
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  component-registry:
    container_name: component-registry
    hostname: component-registry
    image: 192.168.100.242:5012/orspo/rigel/service/component-registry:1.2.7
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${COMPONENT_REGISTRY_PORT}
      - ORIGIN_PATH=/registry/origin
      - UPDATES_PATH=/registry/updates
      - BACKUPS_PATH=/registry/backups
      - FMT_LEVEL=info
    ports:
      - 8090:8090
    volumes:
      - ./component-registry/registry:/registry
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  health-monitor:
    container_name: health-monitor
    hostname: health-monitor
    image: 192.168.100.242:5012/orspo/rigel/service/health-monitor:1.1.7
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - DB_SRV=${DATABASE_SERVICE_ENDPOINT}
      - METRICS_LISTEN_ON=0.0.0.0:${HEALTH_MONITOR_METRICS_EXPORT_PORT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - FMT_LEVEL=trace,hyper=info,reqwest=info,lapin=error,pinky_swear=error,mailbox=info,health_monitor::adapters::node_interactor::node_manager=off,db_service_helper::db_service::subscription::stream=off,health_monitor::application::module=info,db_service_helper::db_service=info
      - LOST_NODE_TIMEOUT=5000
      - MAILBOX_PREFETCH_COUNT=100
    ports:
      - 10000:10000
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  event-monitor:
    container_name: event-monitor
    hostname: event-monitor
    image: 192.168.100.242:5012/orspo/rigel/service/event-monitor:1.2.25
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${EVENT_MONITOR_PORT}
      - DB_SRV=${DATABASE_SERVICE_ENDPOINT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - FMT_LEVEL=info,hyper=off,reqwest=off
      - GELF_LEVEL=info,hyper=off,reqwest=off
      - DAYS_TO_KEEP_EVENTS=30
      # обязательный параметр вместо DB_SRV для версии >= 1.2.0
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/postgres
      - ALERT_EVENTS_LIMIT=2
      - ALERT_EVENTS_LIMIT_FREQUENCY=2
    ports:
      - 8095:8095
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  config-service:
    container_name: config-service
    hostname: config-service
    image: 192.168.100.242:5012/orspo/rigel/service/config-service:1.3.1
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - DB_SRV=${DATABASE_SERVICE_ENDPOINT}
      - BROKER_LOCATION=${RABBITMQ_ENDPOINT}
      - BROKER_USER=${RABBITMQ_USER}
      - BROKER_PASSWORD=${RABBITMQ_PASS}
      - REQUEST_PERIOD=30
      - REPLICATION_TIMEOUT=15
      - TREE_LEVEL=off
      - ADDITIONAL_NODE_CONFIG_PATH=/extra_cfg/log.json
      - REST_PORT=${CONFIG_SERVICE_PORT}
    ports:
      - 18080:18080
    volumes:
      - ./config-service/extra_cfg:/extra_cfg
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  database-service:
    container_name: database-service
    hostname: database-service
    image: 192.168.100.242:5012/orspo/rigel/service/database-service:1.1.61
    ports:
      - 8080:8080
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN_ADDR=0.0.0.0:${DATABASE_SERVICE_PORT}
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/postgres
      - FMT_LEVEL=info
      - GELF_LEVEL=info
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  auth-service:
    container_name: auth-service
    hostname: auth-service
    image: 192.168.100.242:5012/orspo/rigel/service/auth-service:1.2.21
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${AUTH_SERVICE_PORT}
      - CDBS_ENDPOINT=http://${DATABASE_SERVICE_ENDPOINT}
      - FMT_LEVEL=info,lapin=error
      - RSA_PRIVATE_FILE=auth/key.pem
      - JWT_EXPIRE_TIME=300
      - RT_EXPIRE_TIME=86400
      - USER_BLOCK_TIME=15
      - HASH_REQUIRED=true
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/postgres
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    volumes:
      - ./api-gateway/tls-cert:/auth
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  event-combiner:
    container_name: event-combiner
    hostname: event-combiner
    image: 192.168.100.242:5012/orspo/rigel/service/event-combiner:1.0.9
    ports:
      - 12501:12501
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - DATABASE_URL=http://${DATABASE_SERVICE_ENDPOINT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - AUTH_RSA_PUBLIC_FILE=cert/pubkey.pem
      - FMT_LEVEL=info
      - LISTEN=0.0.0.0:12501
    volumes:
      - ./api-gateway/tls-cert:/cert
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  prometheus-discovery:
    container_name: prometheus-discovery
    hostname: prometheus-discovery
    image: 192.168.100.242:5012/orspo/rigel/service/prometheus-discovery:0.2.7
    environment:
      - LISTEN=0.0.0.0:${PROMETHEUS_DISCOVERY_CLI_PORT}
    ports:
      - ${PROMETHEUS_DISCOVERY_CLI_PORT}:${PROMETHEUS_DISCOVERY_CLI_PORT}
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped


  autoheal-service:
    container_name: autoheal-service
    hostname: autoheal-service
    image: 192.168.100.242:5012/orspo/rigel/service/autoheal:latest
    environment:
      - AUTOHEAL_ONLY_MONITOR_RUNNING=true
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  gate-client:
    image: 192.168.100.242:5012/orspo/rigel/service/gate-client:dev
    container_name: gate-client
    restart: unless-stopped
    ports:
      - "8443:443"
      - "8445:445"
      - "8181:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./data/www/dist-front:/usr/share/nginx/html

  mediamtx-web-debug:
    container_name: mediamtx-web-debug
    hostname: mediamtx-web-debug
    image: 192.168.100.242:5012/orspo/rigel/service/mediamtx-webrtc-debug-client:1.0.0
    environment:
      - MEDIAMTX_API_URL=http://192.168.202.9:19997
      - WEBRTC_API_URL=http://192.168.202.9:18889
    ports:
      - 8185:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  hls-web-debug:
    container_name: hls-web-debug
    hostname: hls-web-debug
    image: 192.168.100.242:5012/orspo/rigel/service/hls-debug-client:1.0.0
    environment:
      - API_GATEAWAY_URL=http://192.168.202.10:8189
      - ARCHIVE_DEEP_MINUTES=5
      - TRANSCODE_ENABLED=true
    ports:
      - 8186:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped


networks:
  default:
    external:
      name: external-net

volumes:
  postgresql-data:
