version: '3.3'
services:

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: 192.168.100.242:5012/orspo/rigel/service/rabbitmq:rabbitmq-3.11.0-management
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  postgres:
    container_name: postgres
    hostname: postgres
    image: 192.168.100.242:5012/orspo/rigel/service/postgres-images:postgres-16

    user: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - 5432:5432
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  api-gateway-tls:
    container_name: api-gateway-tls
    hostname: api-gateway-tls
    image: 192.168.100.242:5012/orspo/rigel/service/api-gateway:1.1.9
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${API_GATEWAY_TLS_PORT}
      - PROXYLIST=config/proxylist.yml
      - FMT_LEVEL=info,tower_http=warn
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - TLS_CERT=cert/cert.pem
      - TLS_KEY=cert/key.pem
      - AUTH_RSA_PUBLIC_FILE=cert/pubkey.pem
      - DROP_CONNECTION_WHEN_TOKEN_EXPIRES=no
    ports:
      - 8179:8179
    volumes:
      - ./api-gateway/tls-cert:/cert
      - ./api-gateway/config:/config
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    image: 192.168.100.242:5012/orspo/rigel/service/api-gateway:1.1.9
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${API_GATEWAY_PORT}
      - PROXYLIST=config/proxylist.yml
      - FMT_LEVEL=info,tower_http=warn
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
    ports:
      - 8189:8189
    volumes:
      - ./api-gateway/tls-cert:/cert
      - ./api-gateway/config:/config
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  component-registry:
    container_name: component-registry
    hostname: component-registry
    image: 192.168.100.242:5012/orspo/rigel/service/component-registry:1.2.7
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${COMPONENT_REGISTRY_PORT}
      - ORIGIN_PATH=/registry/origin
      - UPDATES_PATH=/registry/updates
      - BACKUPS_PATH=/registry/backups
      - FMT_LEVEL=info
    ports:
      - 8090:8090
    volumes:
      - ./component-registry/registry:/registry
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  health-monitor:
    container_name: health-monitor
    hostname: health-monitor
    image: 192.168.100.242:5012/orspo/rigel/service/health-monitor:1.1.5
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - DB_SRV=${DATABASE_SERVICE_ENDPOINT}
      - METRICS_LISTEN_ON=0.0.0.0:${HEALTH_MONITOR_METRICS_EXPORT_PORT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - FMT_LEVEL=info,hyper=info,reqwest=info,lapin=error
      - LOST_NODE_TIMEOUT=5000
      - MAILBOX_PREFETCH_COUNT=100
    ports:
      - 10000:10000
    depends_on:
      - database-service
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  event-monitor:
    container_name: event-monitor
    hostname: event-monitor
    image: 192.168.100.242:5012/orspo/rigel/service/event-monitor:1.2.25
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${EVENT_MONITOR_PORT}
      - DB_SRV=${DATABASE_SERVICE_ENDPOINT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - FMT_LEVEL=info,hyper=off,reqwest=off
      - GELF_LEVEL=info,hyper=off,reqwest=off
      - DAYS_TO_KEEP_EVENTS=30
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/postgres
      - MAILBOX_HOST=${GATEWAY_IP}
      - MAILBOX_PORT=${RABBITMQ_CLI_PORT}
    ports:
      - 8095:8095
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  config-service:
    container_name: config-service
    hostname: config-service
    image: 192.168.100.242:5012/orspo/rigel/service/config-service:1.3.1
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - DB_SRV=${DATABASE_SERVICE_ENDPOINT}
      - BROKER_LOCATION=${RABBITMQ_ENDPOINT}
      - BROKER_USER=${RABBITMQ_USER}
      - BROKER_PASSWORD=${RABBITMQ_PASS}
      - REQUEST_PERIOD=30
      - REPLICATION_TIMEOUT=15
      - TREE_LEVEL=off
      - ADDITIONAL_NODE_CONFIG_PATH=/extra_cfg/log.json
      - REST_PORT=${CONFIG_SERVICE_PORT}
    ports:
      - 18080:18080
    volumes:
      - ./config-service/extra_cfg:/extra_cfg
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  database-service:
    container_name: database-service
    hostname: database-service
    image: 192.168.100.242:5012/orspo/rigel/service/database-service:1.1.59
    ports:
      - 8080:8080
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN_ADDR=0.0.0.0:${DATABASE_SERVICE_PORT}
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/postgres
      - FMT_LEVEL=info
      - GELF_LEVEL=info
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  archive-manager:
    privileged: true
    container_name: archive-manager
    hostname: archive-manager
    image: 192.168.100.242:5012/orspo/rigel/service/archive-manager:1.7.24
    #image: archive-manager:1.7.24
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${ARCHIVE_MANAGER_PORT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - FMT_LEVEL=info,lapin=error
      - RECORDER=gst
      - RECORDER_RTSP_BUFFER_MODE=buffer
      - SEGMENT_WRITE_BUFFER=2 MiB
      #- SEGMENT_WRITE_BUFFER=0 KiB
    volumes:
      - /archive:/opt/archive-manager/archive
    #network_mode: "host"
    ports:
      - 9988:9988
      - 8086:8086
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 30G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  auth-service:
    container_name: auth-service
    hostname: auth-service
    image: 192.168.100.242:5012/orspo/rigel/service/auth-service:1.2.20
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${AUTH_SERVICE_PORT}
      - CDBS_ENDPOINT=http://${DATABASE_SERVICE_ENDPOINT}
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/postgres
      - FMT_LEVEL=info,lapin=error
      - RSA_PRIVATE_FILE=auth/key.pem
      - JWT_EXPIRE_TIME=86400
      - RT_EXPIRE_TIME=604800
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - HASH_REQUIRED=true
    ports:
      - 9090:9090
    volumes:
      - ./api-gateway/tls-cert:/auth
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  media-server:
    container_name: media-server
    hostname: media-server
    image: 192.168.100.242:5012/orspo/rigel/service/media-server:1.16.0-alpha.10
    labels:
      - autoheal=true
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - FMT_LEVEL=info
      - SIGNALLER_ADDRESS=ws://${MEDIA_SERVER_IP}:8443
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - BUFFER_LATENCY=0
      - RTSP_PROTO=auto
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  signalling-server:
    container_name: signalling-server
    hostname: signalling-server
    image: 192.168.100.242:5012/orspo/rigel/service/media-server/webrtc-signalling-server:0.10.7f
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  webrtc-www:
    container_name: webrtc-www
    hostname: webrtc-www
    image: 192.168.100.242:5012/orspo/rigel/service/media-server/webrtc-www:1.1.1
    ports:
      - 8099:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  node-manager:
    container_name: node-manager
    hostname: node-manager
    image: 192.168.100.242:5012/orspo/rigel/service/node-runner:1.0.5_1.3.0
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${NODE_MANAGER_PORT}
      - CONFIG=/config/config.json
      - FMT_LEVEL=info
      - GST_PLUGIN_PATH=/opt/node_manager/plugins
    volumes:
      - ./node-manager/config:/config
      - ./node-manager/plugins:/opt/node_manager/plugins
      - ./node-manager/runtime:/opt/node_manager/runtime
    network_mode: host
    depends_on:
      - database-service
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  event-combiner:
    container_name: event-combiner
    hostname: event-combiner
    image: 192.168.100.242:5012/orspo/rigel/service/event-combiner:1.0.9
    ports:
      - 12501:8888
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - DATABASE_URL=http://${DATABASE_SERVICE_ENDPOINT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - AUTH_RSA_PUBLIC_FILE=cert/pubkey.pem
      - LISTEN=0.0.0.0:${EVENT_COMBINER_PORT}
    volumes:
      - ./api-gateway/tls-cert:/cert
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  prometheus-discovery:
    container_name: prometheus-discovery
    hostname: prometheus-discovery
    image: 192.168.100.242:5012/orspo/rigel/service/prometheus-discovery:0.2.7
    environment:
      - LISTEN=0.0.0.0:${PROMETHEUS_DISCOVERY_CLI_PORT}
      - PROMETHEUS_DISCOVERY=http://${GATEWAY_IP}:${PROMETHEUS_DISCOVERY_CLI_PORT}
    ports:
      - 10500:10500
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  autoheal-service:
    container_name: autoheal-service
    hostname: autoheal-service
    image: 192.168.100.242:5012/orspo/rigel/service/autoheal:latest
    environment:
      - AUTOHEAL_ONLY_MONITOR_RUNNING=true
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  gate-client:
    container_name: gate-client
    hostname: gate-client
    image: 192.168.100.242:5012/orspo/rigel/service/gate-client:5.0.75-rc.9
    ports:
      - 8181:80
      - 8445:445
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
 #     - ./data/www/dist-front:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs

  mediamtx-web-debug:
    container_name: mediamtx-web-debug
    hostname: mediamtx-web-debug
    image: 192.168.100.242:5012/orspo/rigel/service/mediamtx-webrtc-debug-client:1.0.0
    environment:
      - MEDIAMTX_API_URL=http://192.168.202.221:9997
      - WEBRTC_API_URL=http://192.168.202.221:8889
    ports:
      - 8185:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  hls-web-debug:
    container_name: hls-web-debug
    hostname: hls-web-debug
    image: 192.168.100.242:5012/orspo/rigel/service/hls-debug-client:1.0.0
    environment:
      - API_GATEAWAY_URL=http://192.168.202.221:8189
      - ARCHIVE_DEEP_MINUTES=5
      - TRANSCODE_ENABLED=true
    ports:
      - 8186:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped

  mediamtx-server:
    hostname: mediamtx_server
    image:  192.168.100.242:5012/orspo/rigel/service/mediamtx:1.11.3
    container_name: mediamtx-server
#    network_mode: "host"
#    privileged: true
#    ulimits:
#      nofile: 65535
#      nproc: 65535
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.202.221
    ports:
      - 9998:9998/tcp
      - 9997:9997/tcp
      - 8889:8889/tcp
      - 8554:8554/tcp
      - 1935:1935/tcp
      - 8189:8189/udp
# rtp      - 8000:8000/udp
#rtcp      - 8001:8001/udp
#      - 49152-65535:49152-65535
    volumes:
      - ./mediamtx_config/mediamtx.yml:/mediamtx.yml
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"

  mediamtx-controller:
    image: 192.168.100.242:5012/orspo/rigel/service/mediamtx-controller:0.2.4
    container_name: mediamtx_controller
    environment:
      - FMT_LEVEL=info,mediamtx_controller=debug,mailbox::amqp_lapin::metrics=off
     # - MEDIAMTX_API=http://192.10.10.1:9997
     # - MEDIAMTX_WEBRTC=http://10.10.10.1:8889
#      - MEDIAMTX_RTSP=rtsp://10.10.10.1:8554
#      - MAILBOX_ADDRS=10.201.0.1:5672
      - MEDIAMTX_API=http://${MEDIA_SERVER_IP}:9997
      - MEDIAMTX_WEBRTC=http://${MEDIA_SERVER_IP}:8889
      - MEDIAMTX_RTSP=rtsp://${MEDIA_SERVER_IP}:8554
      - MAILBOX_ADDRS=192.168.202.221:5672
      - MAILBOX_LOGIN=user
      - MAILBOX_PASSWORD=pass
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"

networks:
  default:
    external:
      name: external-net
  #bond_network:
#    external:
#      name: bond0-macvlan-net
volumes:
  postgresql-data:
  geoserver_data_sxf:
  postgres_data_sxf:
