version: '3.3'
services:

  prometheus-discovery:
    container_name: prometheus-discovery
    hostname: prometheus-discovery
    image: 192.168.100.242:5012/orspo/rigel/service/prometheus-discovery:0.2.7
    environment:
      - LISTEN=0.0.0.0:${PROMETHEUS_DISCOVERY_CLI_PORT}
      - PROMETHEUS_DISCOVERY=http://${GATEWAY_IP}:${PROMETHEUS_DISCOVERY_CLI_PORT}
    ports:
      - 10500:10500
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  node-manager:
    container_name: node-manager
    hostname: node-manager
    image: 192.168.100.242:5012/orspo/rigel/service/node-runner:1.0.5_1.3.0
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${NODE_MANAGER_PORT}
      - CONFIG=/config/config.json
      - FMT_LEVEL=info
      - GST_PLUGIN_PATH=/opt/node_manager/plugins
    volumes:
      - ./node-manager/config:/config
      - ./node-manager/plugins:/opt/node_manager/plugins
      - ./node-manager/runtime:/opt/node_manager/runtime
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:${APP_SERVER_IP}"

  hls-debug-client:
    container_name: hls-debug-client
    hostname: hls-debug-client
    image: 192.168.100.242:5012/orspo/rigel/service/hls-debug-client:1.0.0
    environment:
      - API_GATEAWAY_URL=http://video.server.ru:8189
      - ARCHIVE_DEEP_MINUTES=5
      - TRANSCODE_ENABLED=true
    ports:
      - 8186:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  mediamtx-webrtc-debug-client:
    container_name: mediamtx-webrtc-debug-client
    hostname: mediamtx-webrtc-debug-client
    image: 192.168.100.242:5012/orspo/rigel/service/mediamtx-webrtc-debug-client:1.0.0
    environment:
      - MEDIAMTX_API_URL=http://video.server.ru:9997
      - WEBRTC_API_URL=http://video.server.ru:8889
    ports:
      - 8185:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  archive-manager:
    container_name: archive-manager
    hostname: archive-manager
    image: 192.168.100.242:5012/orspo/rigel/service/archive-manager:1.8.5
    environment:
      - USED_SPACE_LIMIT=300 GiB
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - LISTEN=0.0.0.0:${ARCHIVE_MANAGER_PORT}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - FMT_LEVEL=info,lapin=error,archive_manager=info
    volumes:
      - /archive:/opt/archive-manager/archive
    ports:
      - 9988:9988
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  autoheal-service:
    container_name: autoheal-service
    hostname: autoheal-service
    image: 192.168.100.242:5012/orspo/rigel/service/autoheal:latest
    environment:
      - AUTOHEAL_ONLY_MONITOR_RUNNING=true
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  media-server:
    container_name: media-server
    hostname: media-server
    image: 192.168.100.242:5012/orspo/rigel/service/media-server:1.16.0-alpha.10
    labels:
      - autoheal=true
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
      - FMT_LEVEL=info
      - SIGNALLER_ADDRESS=ws://${MEDIA_SERVER_IP}:8443
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
      - BUFFER_LATENCY=0
      - RTSP_PROTO=auto
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  signalling-server:
    container_name: signalling-server
    hostname: signalling-server
    image: 192.168.100.242:5012/orspo/rigel/service/media-server/webrtc-signalling-server:0.10.7f
    environment:
      - PROMETHEUS_DISCOVERY=http://${DEBUG_SERVICE}
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  webrtc-www:
    container_name: webrtc-www
    hostname: webrtc-www
    image: 192.168.100.242:5012/orspo/rigel/service/media-server/webrtc-www:1.1.1
    ports:
      - 8099:80
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  mediamtx-controller:
    container_name: mediamtx-controller
    hostname: mediamtx-controller
    image: 192.168.100.242:5012/orspo/rigel/service/mediamtx-controller:0.3.2
    environment:
      - FMT_LEVEL=info,mediamtx_controller=debug,mailbox::amqp_lapin::metrics=off
      - MEDIAMTX_CONFIG=/mediamtx_servers.yml
      - MEDIAMTX_WEBRTC=http://${MEDIA_SERVER_IP}:8889
      - MEDIA_SERVER_IP=${MEDIA_SERVER_IP}
      - MAILBOX_ADDRS=${RABBITMQ_ENDPOINT}
      - MAILBOX_LOGIN=${RABBITMQ_USER}
      - MAILBOX_PASSWORD=${RABBITMQ_PASS}
    volumes:
      - /opt/server-video/origin/backend/mediamtx/mediamtx-servers.yml:/mediamtx_servers.yml
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

  mediamtx-server:
    container_name: mediamtx-server
    hostname: mediamtx-server
    image: 192.168.100.242:5012/orspo/rigel/service/mediamtx:1.11.3
    volumes:
      - /opt/server-video/origin/backend/mediamtx/mediamtx.yml:/mediamtx.yml
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 3G
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "200m"
    restart: unless-stopped
    extra_hosts:
      - "server.app.ru:${APP_SERVER_IP}"
      - "server.video.ru:${VIDEO_SERVER_IP}"
      - "server.db.ru:${DB_SAVE_SERVER_IP}"
      - "gate.synerget.ru:10.201.0.1"

networks:
  default:
    external:
      name: server-external-net

