for_grafana = True
with open('D:/work/WHPython/vs90_a5000.yml', 'w') as file:
    file.write('logLevel: info\n')
    file.write('rtspAddress: :8554\n')
    file.write('\n')
    if for_grafana:
        file.write('authInternalUsers:\n')
        file.write('- user: any\n')
        file.write('  pass: \n')
        file.write('  ips: []\n')
        file.write('  permissions:\n')
        file.write('  - action: metrics\n')
        file.write('  - action: publish\n')
        file.write('    path: \n')
        file.write('  - action: read\n')
        file.write('    path: \n')
        file.write('  - action: playback\n')
        file.write('    path: \n')
        file.write('- user: admin\n')
        file.write('  pass: \n')
        file.write('  ips: ["127.0.0.1", "::1"]\n')
        file.write('  permissions:\n')
        file.write('  - action: api\n')
        file.write('  - action: metrics\n')
        file.write('  - action: pprof\n')
        file.write('metrics: yes\n')
        file.write('metricsAddress: :9998\n')
        file.write('metricsEncryption: no\n')
        file.write('metricsAllowOrigin: "*"\n')
    file.write('paths:\n')
    for i in range(1,90):
        file.write(f"  '{i}':\n")
        file.write('    runOnInit: >-\n')
        file.write('      ffmpeg -stream_loop -1 -re -fflags +genpts\n')
        file.write(f'      -i /home/user/2korng/a5000_main.mp4\n')
        file.write('      -c copy\n')
        file.write('      -map 0:v\n')
        file.write('      -f rtsp\n')
        file.write('      -rtsp_transport tcp\n')
        file.write(f'      rtsp://localhost:$RTSP_PORT/{i}\n')
        file.write('    runOnInitRestart: yes\n')
        file.write('\n')
        file.write(f"  '{i}_sub':\n")
        file.write('    runOnInit: >-\n')
        file.write('      ffmpeg -stream_loop -1 -re -fflags +genpts\n')
        file.write(f'      -i /home/user/2korng/sub/a5000_sub.mp4\n')
        file.write('      -c copy\n')
        file.write('      -map 0:v\n')
        file.write('      -f rtsp\n')
        file.write('      -rtsp_transport tcp\n')
        file.write(f'      rtsp://localhost:$RTSP_PORT/{i}_sub\n')
        file.write('    runOnInitRestart: yes\n')
        file.write('\n')
    file.write('protocols: [tcp]\n')
    file.write('readTimeout: "60s"\n')
    file.write('writeTimeout: "60s"\n')
    file.write('readBufferCount: 1024\n')